export const LOGIN_PROMPT = "LOGIN_PROMPT";
export const LOGIN_SUBMIT = "LOGIN_SUBMIT";
export const LOGIN_SETUP = "LOGIN_SETUP";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const DEPOSIT_SHOW_QR = "DEPOSIT_SHOW_QR";
export const DEPOSIT_PENDING = "DEPOSIT_PENDING";
export const DEPOSIT_SUCCESS = "DEPOSIT_SUCCESS";
export const DEPOSIT_FAILURE = "DEPOSIT_FAILURE";

export const WITHDRAW_PROMPT = "WITHDRAW_PROMPT";
export const WITHDRAW_SUBMIT = "WITHDRAW_SUBMIT";
export const WITHDRAW_PENDING = "WITHDRAW_PENDING";
export const WITHDRAW_SUCCESS = "WITHDRAW_SUCCESS";
export const WITHDRAW_FAILURE = "WITHDRAW_FAILURE";
